apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cosmonaut-plugin-trino.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmonaut-plugin-trino.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cosmonaut-plugin-trino.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cosmonaut-plugin-trino.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: plugin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          env:
            - name: COSMONAUT_PLUGIN_ADDR
              value: ":50051"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 3
            periodSeconds: 5
